INSERT INTO club VALUES (1, 'Atalanta');
INSERT INTO club VALUES (2, 'Bologna');
INSERT INTO club VALUES (3, 'Cremonese');

INSERT INTO player (name, position, id_club) VALUES ('Francesco Rossi', 'goalkeeper', 1);
INSERT INTO player (name, position, id_club) VALUES ('Marco Sportiello', 'goalkeeper', 1);
INSERT INTO player (name, position, id_club) VALUES ('Juan Musso', 'goalkeeper', 1);
INSERT INTO player (name, position, id_club) VALUES ('Khadim Ndiaye', 'goalkeeper', 1);
INSERT INTO player (name, position, id_club) VALUES ('Rafael Toloi', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('José Luis Palomino', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Berat Djimsiti', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Joakim Mæhle', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Merih Demiral', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Memeh Caleb Okoli', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Matteo Ruggeri', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Brandon Soppy', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Giorgio Scalvini', 'defender', 1);
INSERT INTO player (name, position, id_club) VALUES ('Marten de Roon', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Davide Zappacosta', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Mario Pasalic', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Ruslan Malinovsky', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Hans Hateboer', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Jeremie Boga', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Simone Muratore', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Teun Koopmeiners', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Éderson', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Nadir Zortea', 'midfielder', 1);
INSERT INTO player (name, position, id_club) VALUES ('Duvan Zapata', 'attacker', 1);
INSERT INTO player (name, position, id_club) VALUES ('Luis Muriel', 'attacker', 1);
INSERT INTO player (name, position, id_club) VALUES ('Ademola Lookman', 'attacker', 1);
INSERT INTO player (name, position, id_club) VALUES ('Rasmus Højlund', 'attacker', 1);
INSERT INTO player (name, position, id_club) VALUES ('Lukas Vorlicky', 'attacker', 1);
INSERT INTO player (name, position, id_club) VALUES ('Lukasz Skorupski', 'goalkeeper', 2);
INSERT INTO player (name, position, id_club) VALUES ('Francesco Bardi', 'goalkeeper', 2);
INSERT INTO player (name, position, id_club) VALUES ('Sebastian Breza', 'goalkeeper', 2);
INSERT INTO player (name, position, id_club) VALUES ('Nicola Bagnolini', 'goalkeeper', 2);
INSERT INTO player (name, position, id_club) VALUES ('Gary Medel', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Adama Soumaoro', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Charalambos Lykogiannis', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Kevin Bonifazi', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Stefan Posch', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Jhon Lucumi', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Gabriele Corbo', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Andrea Cambiaso', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Denso Kasius', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Joaquin Sosa', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Wisdom Amey', 'defender', 2);
INSERT INTO player (name, position, id_club) VALUES ('Lorenzo De Silvestri', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Roberto Soriano', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Nikola Moro', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Jerdy Schouten', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Michel Aebischer', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Emanuel Vignato', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Nicolás Dominguez', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Lewis Ferguson', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Kacper Urbanski', 'midfielder', 2);
INSERT INTO player (name, position, id_club) VALUES ('Marko Arnautovic', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Nicola Sansone', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Riccardo Orsolini', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Orji Okwonkwo', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Musa Barrow', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Musa Juwara', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Joshua Zirkzee', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Antonio Raimondo', 'attacker', 2);
INSERT INTO player (name, position, id_club) VALUES ('Mouhamadou Sarr', 'goalkeeper', 3);
INSERT INTO player (name, position, id_club) VALUES ('Ionut Andrei Radu', 'goalkeeper', 3);
INSERT INTO player (name, position, id_club) VALUES ('Marco Carnesecchi', 'goalkeeper', 3);
INSERT INTO player (name, position, id_club) VALUES ('Gianluca Saro', 'goalkeeper', 3);
INSERT INTO player (name, position, id_club) VALUES ('Dorian Ciezkowski', 'goalkeeper', 3);
INSERT INTO player (name, position, id_club) VALUES ('Vlad Chiriches', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Matteo Bianchetti', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Alex Ferrari', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Paolo Ghiglione', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Jack Hendry', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Leonardo Sernicola', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Luka Lochoshvili', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Emanuele Valeri', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Johan Vásquez', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Emanuel Aiwu', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Giacomo Quagliata', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Maissa Ndiaye', 'defender', 3);
INSERT INTO player (name, position, id_club) VALUES ('Soualiho Meité', 'midfielder', 3);
INSERT INTO player (name, position, id_club) VALUES ('Michele Castagnetti', 'midfielder', 3);
INSERT INTO player (name, position, id_club) VALUES ('Gonzalo Escalante', 'midfielder', 3);
INSERT INTO player (name, position, id_club) VALUES ('Santiago Ascacibar', 'midfielder', 3);
INSERT INTO player (name, position, id_club) VALUES ('Charles Pickel', 'midfielder', 3);
INSERT INTO player (name, position, id_club) VALUES ('Tommaso Milanese', 'midfielder', 3);
INSERT INTO player (name, position, id_club) VALUES ('Christian Acella', 'midfielder', 3);
INSERT INTO player (name, position, id_club) VALUES ('Daniel Ciofani', 'attacker', 3);
INSERT INTO player (name, position, id_club) VALUES ('Jaime Báez', 'attacker', 3);
INSERT INTO player (name, position, id_club) VALUES ('Cristian Buonaiuto', 'attacker', 3);
INSERT INTO player (name, position, id_club) VALUES ('Cyriel Dessers', 'attacker', 3);
INSERT INTO player (name, position, id_club) VALUES ('David Okereke', 'attacker', 3);
INSERT INTO player (name, position, id_club) VALUES ('Luca Zanimacchia', 'attacker', 3);
INSERT INTO player (name, position, id_club) VALUES ('Frank Tsadjout', 'attacker', 3);
INSERT INTO player (name, position, id_club) VALUES ('Felix Afena-Gyan', 'attacker', 3);