INSERT IGNORE INTO club VALUES (1, 'Atalanta');
INSERT IGNORE INTO club VALUES (2, 'Bologna');
INSERT IGNORE INTO club VALUES (3, 'Cremonese');

INSERT IGNORE INTO player VALUES (1, 'Francesco Rossi', 'goalkeeper', 1);
INSERT IGNORE INTO player VALUES (2, 'Marco Sportiello', 'goalkeeper', 1);
INSERT IGNORE INTO player VALUES (3, 'Juan Musso', 'goalkeeper', 1);
INSERT IGNORE INTO player VALUES (4, 'Khadim Ndiaye', 'goalkeeper', 1);
INSERT IGNORE INTO player VALUES (5, 'Rafael Toloi', 'defender', 1);
INSERT IGNORE INTO player VALUES (6, 'José Luis Palomino', 'defender', 1);
INSERT IGNORE INTO player VALUES (7, 'Berat Djimsiti', 'defender', 1);
INSERT IGNORE INTO player VALUES (8, 'Joakim Mæhle', 'defender', 1);
INSERT IGNORE INTO player VALUES (9, 'Merih Demiral', 'defender', 1);
INSERT IGNORE INTO player VALUES (10, 'Memeh Caleb Okoli', 'defender', 1);
INSERT IGNORE INTO player VALUES (11, 'Matteo Ruggeri', 'defender', 1);
INSERT IGNORE INTO player VALUES (12, 'Brandon Soppy', 'defender', 1);
INSERT IGNORE INTO player VALUES (13, 'Giorgio Scalvini', 'defender', 1);
INSERT IGNORE INTO player VALUES (14, 'Marten de Roon', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (15, 'Davide Zappacosta', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (16, 'Mario Pasalic', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (17, 'Ruslan Malinovsky', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (18, 'Hans Hateboer', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (19, 'Jeremie Boga', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (20, 'Simone Muratore', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (21, 'Teun Koopmeiners', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (22, 'Éderson', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (23, 'Nadir Zortea', 'midfielder', 1);
INSERT IGNORE INTO player VALUES (24, 'Duvan Zapata', 'attacker', 1);
INSERT IGNORE INTO player VALUES (25, 'Luis Muriel', 'attacker', 1);
INSERT IGNORE INTO player VALUES (26, 'Ademola Lookman', 'attacker', 1);
INSERT IGNORE INTO player VALUES (27, 'Rasmus Højlund', 'attacker', 1);
INSERT IGNORE INTO player VALUES (28, 'Lukas Vorlicky', 'attacker', 1);
INSERT IGNORE INTO player VALUES (29, 'Lukasz Skorupski', 'goalkeeper', 2);
INSERT IGNORE INTO player VALUES (30, 'Francesco Bardi', 'goalkeeper', 2);
INSERT IGNORE INTO player VALUES (31, 'Sebastian Breza', 'goalkeeper', 2);
INSERT IGNORE INTO player VALUES (32, 'Nicola Bagnolini', 'goalkeeper', 2);
INSERT IGNORE INTO player VALUES (33, 'Gary Medel', 'defender', 2);
INSERT IGNORE INTO player VALUES (34, 'Adama Soumaoro', 'defender', 2);
INSERT IGNORE INTO player VALUES (35, 'Charalambos Lykogiannis', 'defender', 2);
INSERT IGNORE INTO player VALUES (36, 'Kevin Bonifazi', 'defender', 2);
INSERT IGNORE INTO player VALUES (37, 'Stefan Posch', 'defender', 2);
INSERT IGNORE INTO player VALUES (38, 'Jhon Lucumi', 'defender', 2);
INSERT IGNORE INTO player VALUES (39, 'Gabriele Corbo', 'defender', 2);
INSERT IGNORE INTO player VALUES (40, 'Andrea Cambiaso', 'defender', 2);
INSERT IGNORE INTO player VALUES (41, 'Denso Kasius', 'defender', 2);
INSERT IGNORE INTO player VALUES (42, 'Joaquin Sosa', 'defender', 2);
INSERT IGNORE INTO player VALUES (43, 'Wisdom Amey', 'defender', 2);
INSERT IGNORE INTO player VALUES (44, 'Lorenzo De Silvestri', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (45, 'Roberto Soriano', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (46, 'Nikola Moro', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (47, 'Jerdy Schouten', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (48, 'Michel Aebischer', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (49, 'Emanuel Vignato', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (50, 'Nicolás Dominguez', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (51, 'Lewis Ferguson', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (52, 'Kacper Urbanski', 'midfielder', 2);
INSERT IGNORE INTO player VALUES (53, 'Marko Arnautovic', 'attacker', 2);
INSERT IGNORE INTO player VALUES (54, 'Nicola Sansone', 'attacker', 2);
INSERT IGNORE INTO player VALUES (55, 'Riccardo Orsolini', 'attacker', 2);
INSERT IGNORE INTO player VALUES (56, 'Orji Okwonkwo', 'attacker', 2);
INSERT IGNORE INTO player VALUES (57, 'Musa Barrow', 'attacker', 2);
INSERT IGNORE INTO player VALUES (58, 'Musa Juwara', 'attacker', 2);
INSERT IGNORE INTO player VALUES (59, 'Joshua Zirkzee', 'attacker', 2);
INSERT IGNORE INTO player VALUES (60, 'Antonio Raimondo', 'attacker', 2);
INSERT IGNORE INTO player VALUES (61, 'Mouhamadou Sarr', 'goalkeeper', 3);
INSERT IGNORE INTO player VALUES (62, 'Ionut Andrei Radu', 'goalkeeper', 3);
INSERT IGNORE INTO player VALUES (63, 'Marco Carnesecchi', 'goalkeeper', 3);
INSERT IGNORE INTO player VALUES (64, 'Gianluca Saro', 'goalkeeper', 3);
INSERT IGNORE INTO player VALUES (65, 'Dorian Ciezkowski', 'goalkeeper', 3);
INSERT IGNORE INTO player VALUES (66, 'Vlad Chiriches', 'defender', 3);
INSERT IGNORE INTO player VALUES (67, 'Matteo Bianchetti', 'defender', 3);
INSERT IGNORE INTO player VALUES (68, 'Alex Ferrari', 'defender', 3);
INSERT IGNORE INTO player VALUES (69, 'Paolo Ghiglione', 'defender', 3);
INSERT IGNORE INTO player VALUES (70, 'Jack Hendry', 'defender', 3);
INSERT IGNORE INTO player VALUES (71, 'Leonardo Sernicola', 'defender', 3);
INSERT IGNORE INTO player VALUES (72, 'Luka Lochoshvili', 'defender', 3);
INSERT IGNORE INTO player VALUES (73, 'Emanuele Valeri', 'defender', 3);
INSERT IGNORE INTO player VALUES (74, 'Johan Vásquez', 'defender', 3);
INSERT IGNORE INTO player VALUES (75, 'Emanuel Aiwu', 'defender', 3);
INSERT IGNORE INTO player VALUES (76, 'Giacomo Quagliata', 'defender', 3);
INSERT IGNORE INTO player VALUES (77, 'Maissa Ndiaye', 'defender', 3);
INSERT IGNORE INTO player VALUES (78, 'Soualiho Meité', 'midfielder', 3);
INSERT IGNORE INTO player VALUES (79, 'Michele Castagnetti', 'midfielder', 3);
INSERT IGNORE INTO player VALUES (80, 'Gonzalo Escalante', 'midfielder', 3);
INSERT IGNORE INTO player VALUES (81, 'Santiago Ascacibar', 'midfielder', 3);
INSERT IGNORE INTO player VALUES (82, 'Charles Pickel', 'midfielder', 3);
INSERT IGNORE INTO player VALUES (83, 'Tommaso Milanese', 'midfielder', 3);
INSERT IGNORE INTO player VALUES (84, 'Christian Acella', 'midfielder', 3);
INSERT IGNORE INTO player VALUES (85, 'Daniel Ciofani', 'attacker', 3);
INSERT IGNORE INTO player VALUES (86, 'Jaime Báez', 'attacker', 3);
INSERT IGNORE INTO player VALUES (87, 'Cristian Buonaiuto', 'attacker', 3);
INSERT IGNORE INTO player VALUES (88, 'Cyriel Dessers', 'attacker', 3);
INSERT IGNORE INTO player VALUES (89, 'David Okereke', 'attacker', 3);
INSERT IGNORE INTO player VALUES (90, 'Luca Zanimacchia', 'attacker', 3);
INSERT IGNORE INTO player VALUES (91, 'Frank Tsadjout', 'attacker', 3);
INSERT IGNORE INTO player VALUES (92, 'Felix Afena-Gyan', 'attacker', 3);