USE calcio;

DROP TABLE IF EXISTS club;
CREATE TABLE club (
         id INT AUTO_INCREMENT PRIMARY KEY,
         name VARCHAR(255) NOT NULL)
ENGINE=INNODB;

DROP TABLE IF EXISTS player;
CREATE TABLE player (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    id_club INT NOT NULL,
    FOREIGN KEY (id_club) REFERENCES club(id) ON DELETE CASCADE,
    INDEX position_club (position, id_club))
ENGINE=INNODB;